// ────────────────────────────────────────────────────────────────
// Oryvia — AI Orchestrator
//
// Intent router for the stylist chat. Deterministic, private local
// engine by default. When OPENAI_API_KEY / ANTHROPIC_API_KEY /
// GOOGLE_GENERATIVE_AI_API_KEY are set, the conversational text is
// generated by the cloud model while the structured actions
// (outfit / shopping / insights) remain deterministic for safety.
// ────────────────────────────────────────────────────────────────

import {
  analyzeInspirations,
  effectiveStyleDna,
  generateOutfit,
  generateShopping,
} from "./recommend";
import { getWeather, geocodeCity } from "./weather";
import * as repo from "./repo";
import type { OutfitLook, ShoppingItem, WeatherInfo } from "./types";
import { archetypeMap } from "./fashion";
import { nearestColor } from "./palette";

export interface ChatReply {
  text: string;
  kind: "chat" | "outfit" | "shopping" | "insight";
  outfit?: { occasion: string; look: OutfitLook; alternatives: OutfitLook[]; outfitId: string };
  shopping?: { goal: string; budget: number; style: string; items: ShoppingItem[]; total: number };
  weather?: WeatherInfo;
}

interface Ctx {
  userId: string;
  name: string | null;
  body: NonNullable<ReturnType<typeof repo.findUserById>>["user"]["bodyProfile"];
  dna: NonNullable<ReturnType<typeof repo.findUserById>>["user"]["styleDna"];
  closet: ReturnType<typeof repo.listCloset>;
  inspirations: ReturnType<typeof repo.listInspiration>;
  feedback: ReturnType<typeof repo.listOutfitFeedback>;
}

function loadCtx(userId: string): Ctx {
  const row = repo.findUserById(userId)!;
  return {
    userId,
    name: row.user.name,
    body: row.user.bodyProfile,
    dna: row.user.styleDna,
    closet: repo.listCloset(userId),
    inspirations: repo.listInspiration(userId),
    feedback: repo.listOutfitFeedback(userId),
  };
}

function effectiveDna(ctx: Ctx) {
  return ctx.dna ? effectiveStyleDna(ctx.dna, ctx.feedback) : null;
}

// ── intent detection ────────────────────────────────────────────

type Intent =
  | "outfit"
  | "shopping"
  | "advice"
  | "inspiration"
  | "closet"
  | "greeting"
  | "chat";

function detectIntent(text: string): Intent {
  const t = text.toLowerCase();
  if (/(bonjour|salut|hello|coucou|hey|bonsoir)\b/.test(t)) return "greeting";
  if (/(achat|acheter|shopping|budget|euros|€|am[ée]liorer|upgrade|compl[ée]ter|il me manque)/.test(t)) return "shopping";
  if (/(tenue|outfit|look|mariage|rendez-?vous|date\b|soir[ée]e|business|entretien|boulot|travail|sport|voyage|quotidien|habiller|porter|m'habiller|habit)/.test(t)) return "outfit";
  if (/(pinterest|instagram|inspiration|inspire|tendance|proposer des styles|style que|r[ée]f[ée]rence)/.test(t)) return "inspiration";
  if (/(morphologie|corps|silhouette|taille|quelle couleur|me va|conseil|me mettre|flatte)/.test(t)) return "advice";
  if (/(combien|dressing|garde-?robe|armoire|placard|v[êe]tements)/.test(t)) return "closet";
  return "chat";
}

const OCCASION_WORDS: Record<string, string[]> = {
  wedding: ["mariage"],
  date: ["rendez", "date", "rencard"],
  business: ["business", "entretien", "boulot", "travail", "bureau", "client"],
  party: ["soirée", "soir", "fête", "anniversaire"],
  sport: ["sport", "gym", "running", "footing"],
  interview: ["entretien", "recrutement"],
  travel: ["voyage", "vacances", "week-end", "weekend"],
  everyday: ["quotidien", "tous les jours", "casual", "décontracté"],
};

function detectOccasion(text: string): string {
  const t = text.toLowerCase();
  for (const [key, words] of Object.entries(OCCASION_WORDS)) {
    if (words.some((w) => t.includes(w))) return key;
  }
  return "everyday";
}

function detectCity(text: string): string | null {
  const m = text.match(/(?:à|a|pour|sur)\s+([A-ZÀ-ÖØ-öø-ÿ][a-zà-öø-ÿ'-]{2,})/);
  if (!m) return null;
  const city = m[1];
  // Exclude obviously non-city matches.
  if (/(tenue|outfit|look|style|soir|sport|bureau)/i.test(city)) return null;
  return city;
}

function detectBudget(text: string): number | null {
  const m = text.match(/(\d{2,5})\s*(?:€|euros?)/);
  if (m) return parseInt(m[1], 10);
  const m2 = text.match(/(\d{2,5})\s*euros?/);
  if (m2) return parseInt(m2[1], 10);
  return null;
}

// ── local composer ──────────────────────────────────────────────

function localText(intent: Intent, ctx: Ctx, extra: { weather?: WeatherInfo | null } = {}): string {
  const name = ctx.name ? ` ${ctx.name}` : "";
  const closetN = ctx.closet.length;
  const topArchetype = ctx.dna
    ? Object.entries(ctx.dna.archetypes).sort((a, b) => b[1] - a[1])[0]
    : null;
  const archLabel = topArchetype ? archetypeMap.get(topArchetype[0])?.label.toLowerCase() : "minimal";
  const w = extra.weather;

  switch (intent) {
    case "greeting":
      return `Bonjour${name} 👋 Je suis Oryvia, ton styliste personnel. Je connais déjà ta morphologie, ta palette et ton dressing (${closetN} pièce${closetN > 1 ? "s" : ""}). Demande-moi une tenue pour une occasion, des idées shopping, ou laisse-moi décrypter tes inspirations.`;
    case "closet":
      return `Ton dressing compte ${closetN} pièce${closetN > 1 ? "s" : ""}. ${ctx.dna ? `Ta signature « ${ctx.dna.vibe.split("—")[0].trim()} » me permet déjà de composer des tenues cohérentes.` : ""} Ajoute encore quelques pièces ou des inspirations pour affiner tes recommandations.`;
    case "advice":
      if (!ctx.body) return `Complète d'abord ton profil corps dans les réglages pour que je puisse te conseiller précisément sur les coupes et les couleurs.`;
      if (ctx.dna) {
        const palette = ctx.dna.palette.map((c) => nearestColor(c).name.toLowerCase()).slice(0, 6).join(", ");
        return `Ta morphologie et ta palette me disent déjà beaucoup. Tes couleurs fortes : ${palette}. Je m'appuie dessus pour chaque tenue — demande-moi un look et tu verras.`;
      }
      return `Je peux t'aider : dis-moi une occasion (mariage, bureau, soirée…) et je te compose une tenue adaptée à ta morphologie.`;
    case "inspiration": {
      if (ctx.inspirations.length === 0) return `Tu n'as pas encore ajouté d'inspirations. Envoie des photos Pinterest/Instagram dans la section Inspiration, et je détecterai tes couleurs, tes styles et les pièces à ajouter à ton dressing.`;
      const insight = analyzeInspirations(ctx.inspirations, ctx.closet);
      return `${insight.summary} ${insight.colorGaps.length ? `Il te manque du ${insight.colorGaps.map((c) => nearestColor(c).name.toLowerCase()).join(", ")} pour recréer ces looks avec ton dressing actuel.` : "Ton dressing couvre déjà bien ces couleurs."}`;
    }
    case "chat":
      return `Bonne idée${name}. Je peux composer une tenue (dis-moi l'occasion), faire une liste shopping avec un budget, ou analyser tes inspirations. Que préfères-tu ?`;
    case "outfit":
      return `Voici la tenue que je te propose${w ? `, calée sur la météo ${w.city ? `de ${w.city} ` : ""}(${w.description.toLowerCase()}, ${w.tempC}°C)` : ""}.`;
    case "shopping":
      return `Voici ma sélection, pensée pour ton style ${archLabel} et tes manques actuels.`;
  }
}

// ── cloud providers (optional) ──────────────────────────────────

async function callProvider(intent: Intent, userText: string, ctx: Ctx, extra: { weather?: WeatherInfo | null }): Promise<string | null> {
  const key = process.env.OPENAI_API_KEY || process.env.ANTHROPIC_API_KEY || process.env.GOOGLE_GENERATIVE_AI_API_KEY;
  if (!key) return null;

  const system = `Tu es Oryvia, un styliste IA personnel français, chaleureux et précis.
Contexte utilisateur :
- Nom : ${ctx.name ?? "inconnu"}
- Morphologie : ${ctx.body?.bodyShape ?? "inconnue"} (${ctx.body?.heightCm ?? "?"} cm, ${ctx.body?.weightKg ?? "?"} kg)
- Style DNA : ${ctx.dna ? ctx.dna.vibe : "pas encore défini"}
- Palette : ${ctx.dna?.palette.join(", ") ?? "—"}
- Dressing : ${ctx.closet.length} pièces
- Météo : ${extra.weather ? `${extra.weather.description}, ${extra.weather.tempC}°C à ${extra.weather.city || "?"}` : "inconnue"}

Réponds en français, 3 à 5 phrases maximum, concret et utile. Ne mentionne pas que tu es une IA cloud.`;
  const prompt = `Intention détectée : ${intent}. Message utilisateur : "${userText}"`;

  try {
    if (process.env.OPENAI_API_KEY) {
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        signal: AbortSignal.timeout(25000),
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${process.env.OPENAI_API_KEY}` },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          messages: [
            { role: "system", content: system },
            { role: "user", content: prompt },
          ],
          max_tokens: 400,
        }),
      });
      if (res.ok) {
        const json = (await res.json()) as { choices?: { message?: { content?: string } }[] };
        const text = json.choices?.[0]?.message?.content?.trim();
        if (text) return text;
      }
    }
    if (process.env.ANTHROPIC_API_KEY) {
      const res = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        signal: AbortSignal.timeout(25000),
        headers: {
          "Content-Type": "application/json",
          "x-api-key": process.env.ANTHROPIC_API_KEY,
          "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
          model: "claude-3-haiku-20240307",
          max_tokens: 400,
          system,
          messages: [{ role: "user", content: prompt }],
        }),
      });
      if (res.ok) {
        const json = (await res.json()) as { content?: { type: string; text?: string }[] };
        const text = json.content?.find((c) => c.type === "text")?.text?.trim();
        if (text) return text;
      }
    }
    if (process.env.GOOGLE_GENERATIVE_AI_API_KEY) {
      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${process.env.GOOGLE_GENERATIVE_AI_API_KEY}`,
        {
          method: "POST",
          signal: AbortSignal.timeout(25000),
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            systemInstruction: { parts: [{ text: system }] },
            contents: [{ role: "user", parts: [{ text: prompt }] }],
          }),
        }
      );
      if (res.ok) {
        const json = (await res.json()) as { candidates?: { content?: { parts?: { text?: string }[] } }[] };
        const text = json.candidates?.[0]?.content?.parts?.map((p) => p.text).join("")?.trim();
        if (text) return text;
      }
    }
  } catch {
    // fall through to local
  }
  return null;
}

// ── main entry ──────────────────────────────────────────────────

export async function answerChat(userId: string, text: string): Promise<ChatReply> {
  const ctx = loadCtx(userId);
  const intent = detectIntent(text);

  let weather: WeatherInfo | null = null;
  const city = detectCity(text);
  if ((intent === "outfit" || intent === "shopping") && city) {
    const geo = await geocodeCity(city);
    if (geo) {
      weather = await getWeather(geo.latitude, geo.longitude);
      if (weather) weather.city = geo.name;
    }
  }

  // Structured actions are always computed locally (deterministic).
  if (intent === "outfit") {
    const occasion = detectOccasion(text);
    const { look, alternatives } = generateOutfit({
      body: ctx.body,
      dna: effectiveDna(ctx),
      closet: ctx.closet,
      occasion,
      weather,
      city,
      styleHint: text,
    });
    // Persist so the user can like/dislike it and refine their DNA.
    const saved = repo.addOutfit(ctx.userId, { occasion, city, look, alternatives });
    const cloud = await callProvider(intent, text, ctx, { weather });
    return {
      kind: "outfit",
      text: cloud ?? localText(intent, ctx, { weather }),
      outfit: { occasion, look, alternatives, outfitId: saved.id },
      weather: weather ?? undefined,
    };
  }

  if (intent === "shopping") {
    const budget = detectBudget(text) ?? ctx.dna?.budget ?? 300;
    const { items, total } = generateShopping({
      dna: effectiveDna(ctx),
      body: ctx.body,
      closet: ctx.closet,
      budget,
      goal: text,
      style: text,
    });
    const cloud = await callProvider(intent, text, ctx, { weather });
    return {
      kind: "shopping",
      text: cloud ?? localText(intent, ctx, { weather }),
      shopping: { goal: text, budget, style: text, items, total },
    };
  }

  if (intent === "inspiration") {
    const cloud = await callProvider(intent, text, ctx, { weather });
    return { kind: "insight", text: cloud ?? localText(intent, ctx, { weather }) };
  }

  const cloud = await callProvider(intent, text, ctx, { weather });
  return { kind: "chat", text: cloud ?? localText(intent, ctx, { weather }) };
}
